version: '3.1'

services:
  api:
    image: nodepki-api:7.0
    environment:
      - ROOT_PASSPHRASE="123456789"
      - ROOT_CA_COMMON_NAME="Private Root CA"
      - INTERMEDIATE_PASSPHRASE="123456789" 
      - INTERMEDIATE_CA_COMMON_NAME="Private Intermediate CA"
      - OCSP_PASSPHRASE="123456789"
      - COUNTRY_CODE=DE
      - STATE_NAME=RLP
      - LOCALITY_NAME=RLP
      - ORGANIZATION_NAME=private
      - WEBUI_USER=admin
      - WEBUI_PASS=admin
